### ISSUE TITLE
excuse me. .Android termux app

### ISSUE THREAD

**Issue by ghost** [j0fiN/pcmd#2]
![Screenshot_20210516-224524.png](https://user-images.githubusercontent.com/26930526/118401518-9b329600-b698-11eb-90a2-6c0c73fe3df4.png)

It's strange, I can't think of what's wrong.

**Comment by j0fiN** [comment]
@mySaYo 
Can you add some commands in your `cmd.yaml` and then run `pcmd list`?
An Example so that you can copy,
```yaml
hi: echo "Hi from pcmd"
test: ls
```

**Comment by ghost** [comment]
> @mySaYo 
> Can you add some commands in your `cmd.yaml` and then run `pcmd list`?
> An Example so that you can copy,
> ```yaml
> hi: echo "Hi from pcmd"
> test: ls
> ```

vim cmd.yaml

pcmd run hi
FileNotFound: Please make sure that your file name is 'cmd.yaml'

cat cmd.yaml
hi: echo "Hi from pcmd"
test: ls

pcmd run test
FileNotFound: Please make sure that your file name is 'cmd.yaml'

**Comment by j0fiN** [comment]
@mySaYo 
Please upgrade the package and check now.
```sh-session
pip install -U pcmd
```

**Comment by ghost** [comment]
> @mySaYo 
> Please upgrade the package and check now.
> ```sh-session
> pip install -U pcmd
> ```

![Screenshot_20210516233315.jpg](https://user-images.githubusercontent.com/26930526/118403033-1dbe5400-b69f-11eb-9ca4-3e8422758eed.jpg)

All right! Great!

**Comment by j0fiN** [comment]
@mySaYo 
Thanks for reporting these issues.

> Note that an empty `cmd.yaml` file will also show an output of `FileNotFound`
